name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install root dependencies
        run: npm ci

      - name: Install Expo CLI globally
        run: npm install -g expo-cli

      - name: Install project dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Prebuild Expo project
        run: npx expo prebuild --platform android

      - name: Build Android APK with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 5
